name: Release App

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: Build and Release (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Build and Publish Electron App
        run: bun run package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}